version: '2'
services:
  factorio:
    build:
      context: .
      args:
        # Check buildinfo.json for supported versions and SHAs
        # https://github.com/factoriotools/factorio-docker/blob/master/buildinfo.json
        - VERSION=1.1.110
        - SHA256=485fe6db36e5decd7dd0d70e7c97e61f818100fa3e48d87884b287027c7a646a
    ports:
      - "34197:34197/udp"
      - "27015:27015/tcp"
    volumes:
      - /opt/factorio:/factorio
    environment:
      - LOAD_LATEST_SAVE=true
      - GENERATE_NEW_SAVE=true
      - SAVE_NAME=IR3_SAVE
      - UPDATE_MODS_ON_START=false
      - USERNAME=Inger_Pro
      - TOKEN=ba4cce47d034c8b0e36b4cf9a2c5ec
      - DLC_SPACE_AGE=false